answers:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: giiotpf-ot29206
      #account: cmu-data
      
      # User/password auth
      user: ken370
      password: Maxcasper1

      role: accountadmin
      database: dbt_learning
      warehouse: compute_wh
      schema: staging
      #client_session_keep_alive: TRUE
      threads: 8    
