answers:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: xz19767
      #account: cmu-data
      

      # User/password auth
      user: kentorres822@gmail.com
      password: Maxcasper1

      role: accountadmin
      database: dbt_learning
      warehouse: compute_wh
      schema: staging
      #client_session_keep_alive: TRUE
      threads: 8    
